MAD-1-Grocery Store V1/grocery_app/views.py
from flask import Blueprint, render_template,request,redirect,url_for,flash,session
from .models import Category, Product,User,CartItem,PurchaseHistory
from flask_login import login_required, current_user
from . import db
from datetime import datetime


views = Blueprint('views',__name__)

@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    # Get all categories and associated products
    categories = Category.query.all()
    products = Product.query.all()
    return render_template("home.html", categories=categories, products=products)

@views.route('/adminhome', methods=['GET', 'POST'])
@login_required
def adminhome():
    # Get all categories created by the admin
    categories = Category.query.filter_by(admin_id=current_user.id).all()
    return render_template("admin_home.html", categories=categories)

# Create a new category
@views.route('/admin/categories/create', methods=['GET', 'POST'])
@login_required
def create_category():
    if request.method == 'POST':
        name = request.form['name']

        # Get the ID of the currently logged-in admin
        admin_id = current_user.id

        # Check if the category already exists
        existing_category = Category.query.filter_by(name=name, admin_id=admin_id).first()
        if existing_category:
            flash('Category already exists.', 'error')
            return redirect(url_for('views.list_categories'))
        
        category = Category(name=name,admin_id=admin_id)
        db.session.add(category)
        db.session.commit()

        flash('Category created successfully.', 'success')
        return redirect(url_for('views.adminhome'))

    return render_template('create_category.html')

# Read (list) all categories
@views.route('/admin/categories')
@login_required
def list_categories():
    categories = Category.query.all()
    return render_template('list_categories.html', categories=categories)

# Update an existing category
@views.route('/admin/categories/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    category = Category.query.get(category_id)

    if request.method == 'POST':
        category.name = request.form['name']
        db.session.commit()

        flash('Category updated successfully.', 'success')
        return redirect(url_for('views.list_categories'))

    return render_template('edit_category.html', category=category)

# Delete an existing category
@views.route('/admin/categories/<int:category_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get(category_id)

    if request.method == 'POST':
        db.session.delete(category)
        db.session.commit()

        flash('Category deleted successfully.', 'success')
        return redirect(url_for('views.list_categories'))

    return render_template('delete_category.html', category=category)


# Create a new product
@views.route('/admin/products/create', methods=['GET', 'POST'])
@login_required
def create_product():
    if request.method == 'POST':
        name = request.form['name']
        rate_per_unit = float(request.form['rate_per_unit'])
        quantity = float(request.form['quantity'])
        section_id = int(request.form['section'])
        unit=request.form['unit'] 
        expiration_date_str = request.form['expiration_date']

        # Convert the string to a Python date object
        try:
            expiration_date = datetime.strptime(expiration_date_str, '%Y-%m-%d').date()
        except ValueError:
            expiration_date = None  # Handle the case when the date format is invalid

        product = Product(name=name, rate_per_unit=rate_per_unit, quantity=quantity, section_id=section_id,unit=unit,expiration_date=expiration_date)
        db.session.add(product)
        db.session.commit()

        flash('Product created successfully.', 'success')
        return redirect(url_for('views.list_products'))

    sections = Category.query.all()
    return render_template('create_product.html', sections=sections)

# Read (list) all products
@views.route('/admin/products')
@login_required
def list_products():
    products = Product.query.all()
    return render_template('list_products.html', products=products)

# Update an existing product
@views.route('/admin/products/<int:product_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_product(product_id):
    product = Product.query.get(product_id)
    sections = Category.query.all()

    if request.method == 'POST':
        product.name = request.form['name']
        product.rate_per_unit = float(request.form['rate_per_unit'])
        product.quantity = float(request.form['quantity'])
        product.section_id = int(request.form['section'])
        
        # Assuming you have the expiration date as a string from the form or request
        expiration_date_str = request.form['expiration_date']

        # Convert the string to a Python date object
        try:
            expiration_date = datetime.strptime(expiration_date_str, '%Y-%m-%d').date()
        except ValueError:
            expiration_date = None  # Handle the case when the date format is invalid

        # Now you can use the expiration_date in your update
        product = Product.query.get(product_id)
        if product:
            # Update the product's rate_per_unit and expiration_date
            product.rate_per_unit = float(request.form['rate_per_unit'])
            product.expiration_date = expiration_date

        db.session.commit()

        flash('Product updated successfully.', 'success')
        return redirect(url_for('views.list_products'))

    return render_template('edit_product.html', product=product, sections=sections)

# Delete an existing product
@views.route('/admin/products/<int:product_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_product(product_id):
    product = Product.query.get(product_id)

    if request.method == 'POST':
        db.session.delete(product)
        db.session.commit()

        flash('Product deleted successfully.', 'success')
        return redirect(url_for('views.list_products'))

    return render_template('delete_product.html', product=product)

# Search for sections/categories or products based on search_type
@views.route('/search', methods=['GET'])
def search():
    query = request.args.get('q', '')
    search_type = request.args.get('search_type', 'sections')  # Default to searching sections

    if search_type == 'sections':
        sections = Category.query.filter(Category.name.contains(query)).all()
        # Fetch the available sections for the dropdown
        sections = Category.query.filter(Category.name.contains(query)).all() # Fetch all sections
        return render_template('search_result.html', query=query, sections=sections, available_sections=sections)

    elif search_type == 'products':
        section_search = request.args.get('section_search')  # Get the selected section
        if section_search:
            products = Product.query.filter(
                Product.name.contains(query),
                Product.section.has(name=section_search)
            ).all()
        else:
            products = Product.query.filter(Product.name.contains(query) | Product.rate_per_unit.contains(query)).all()
        return render_template('search_result.html', query=query, products=products, section_search=section_search)




@views.route('/add_to_cart/<int:product_id>', methods=['POST'])
@login_required
def add_to_cart(product_id):
    user_id = current_user.id
    quantity = int(request.form['quantity'])

    # Retrieve the product from the database
    product = Product.query.get(product_id)

    # Check if the product exists and if it has an expiration date
    if product and product.expiration_date:
        # Get the current date
        current_date = datetime.now().date()

        # Check if the product has expired
        if product.expiration_date < current_date:
            flash('Product has expired and cannot be added to the cart.', 'danger')
            return redirect(url_for('views.home'))

    # Check if the product is in stock
    if product and product.quantity >= quantity:
        # Check if the product is already in the cart
        cart_item = CartItem.query.filter_by(user_id=user_id, product_id=product_id).first()
        if cart_item:
            cart_item.quantity += quantity
        else:
            cart_item = CartItem(user_id=user_id, product_id=product_id, quantity=quantity)
            db.session.add(cart_item)

        db.session.commit()
        flash('Product added to cart.', 'success')
    else:
        flash('Insufficient quantity or the product does not exist.', 'danger')

    return redirect(url_for('views.home'))


@views.route('/remove_from_cart/<int:product_id>', methods=['GET'])
@login_required
def remove_from_cart(product_id):
    user_id = current_user.id
    cart_item = CartItem.query.filter_by(user_id=user_id, product_id=product_id).first()

    if cart_item:
        db.session.delete(cart_item)
        db.session.commit()
        flash('Product removed from cart.', 'success')

    return redirect(url_for('views.view_cart'))


@views.route('/cart', methods=['GET'])
@login_required
def view_cart():
    user_id = current_user.id
    cart_items = CartItem.query.filter_by(user_id=user_id).all()
    total_amount = sum(cart_item.product.rate_per_unit * cart_item.quantity for cart_item in cart_items)

    return render_template('view_cart.html', cart_items=cart_items, total_amount=total_amount)



@views.route('/buy_all', methods=['GET', 'POST'])
@login_required
def buy_all():
    user_id = current_user.id
    cart_items = CartItem.query.filter_by(user_id=user_id).all()

    if request.method == 'POST':
        # Perform the purchase logic here, e.g., update product quantities, create orders, etc.
        for cart_item in cart_items:

MAD-1-Grocery Store V1/grocery_app/templates/admin_nav.html
<!-- admin_nav.html -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
            <a class="nav-item nav-link" id="home" href="/adminhome">Home</a>
            <a class="nav-item nav-link" id="summary" href="/summary">Summary</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        </div>
    </div>
</nav>

MAD-1-Grocery Store V1/grocery_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title> {% block title %}Base{% endblock %} </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dar bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="colapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <a class="nav-item nav-link" id="login" href="/">Login</a>
                <a class="nav-item nav-link" id="signup" href="/signup">SignUp</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            </div>
        </div>
    </nav>


    {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
    
    
    
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
        type="text/javascript"
        src="{{ url_for('static',filename='index.js')}}"
    ></script>
</body>
</html>

MAD-1-Grocery Store V1/grocery_app/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha256-iWVgyhZB1ho2PYkWpxQMDiH4/vvaUTLCZBXG5aKMmQU=" crossorigin="anonymous" />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title> {% block title %}Base{% endblock %} </title>
      <!-- Include the Plotly.js library -->
      <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  
</head>
<body>
  {% if current_user.is_authenticated %}
        {% if current_user.is_manager %}
              {% include 'admin_nav.html' %}
        {% else %}
        {% with categories=categories %}
        {% include 'user_nav.html' %}
    {% endwith %}
        {% endif %}
{% endif %}


    {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}
    
    
    
    
        {% block content %}
        {% endblock %}
    


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
        type="text/javascript"
        src="{{ url_for('static',filename='index.js')}}"
    ></script>
</body>
</html>

MAD-1-Grocery Store V1/grocery_app/templates/buy_all.html
{% extends "base2.html" %}

{% block content %}
    <h1>Confirm Purchase</h1>
    <table>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>

        <!-- buy_all.html -->
        {% for cart_item in cart_items %}
        <tr>
            <td>{{ cart_item.product.name }}</td>
            <td>${{ cart_item.product.rate_per_unit }}</td>
            <td>{{ cart_item.quantity }}</td>
            <td>${{ cart_item.product.rate_per_unit * cart_item.quantity }}</td>
        </tr>
        {% endfor %}
    </table>

    <p class="total-amount">Total Amount: Rs.{{ total_amount }}</p>

    <form action="{{ url_for('views.buy_all') }}" method="post">
        <button type="submit" class="btn btn-success">Confirm Purchase</button>
    </form>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/create_category.html
<!-- app/templates/create_category.html -->

{% extends "base2.html" %}

{% block content %}
    <h1>Create New Category</h1>
    <form method="POST" action="{{ url_for('views.create_category') }}">
        <label for="name">Category Name:</label>
        <input type="text" id="name" name="name" required>
        <br>
        <input type="submit" value="Create">
    </form>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/create_product.html
{% extends "base2.html" %}

{% block content %}
    <h1>Create New Product</h1>
    <form method="POST" action="{{ url_for('views.create_product') }}">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required>
        <br>
        <label for="rate_per_unit">Rate per Unit:</label>
        <input type="number" step="0.01" id="rate_per_unit" name="rate_per_unit" required>
        <br>
        <label for="quantity">Quantity:</label>
        <input type="number" step="0.01" id="quantity" name="quantity" required>
        <br>
        <label for="section">Section:</label>
        <select id="section" name="section">
            {% for section in sections %}
                <option value="{{ section.id }}">{{ section.name }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="unit">Unit:</label>
        <select id="unit" name="unit">
            <option value="Rs/kg">Rs/kg</option>
            <option value="Rs/liter">Rs/liter</option>
            <option value="Rs/dozen">Rs/dozen</option>
            <option value="Rs/gram">Rs/gram</option>
            <!-- Add other unit options as needed -->
        </select>
        <br>
        <label for="">expiration_date:</label>
        <input type="text" id="expiration_date" name="expiration_date" required>
        <br>
        <input type="submit" value="Create">
    </form>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/delete_category.html
<!-- app/templates/delete_category.html -->

{% extends "base2.html" %}

{% block content %}
    <h1>Delete Category</h1>
    <p>Are you sure you want to delete the category "{{ category.name }}"?</p>
    <form method="POST" action="{{ url_for('views.delete_category', category_id=category.id) }}">
        <input type="submit" value="Delete">
    </form>
    <a href="{{ url_for('views.list_categories') }}">Cancel</a>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/delete_product.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Product</h1>
    <p>Are you sure you want to delete the product "{{ product.name }}"?</p>
    <form method="POST" action="{{ url_for('views.delete_product', product_id=product.id) }}">
        <input type="submit" value="Delete">
    </form>
    <a href="{{ url_for('views.list_products') }}">Cancel</a>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/edit_category.html
<!-- app/templates/edit_category.html -->

{% extends "base2.html" %}

{% block content %}
    <h1>Edit Category</h1>
    <form method="POST" action="{{ url_for('views.edit_category', category_id=category.id) }}">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" value="{{ category.name }}" required>
        <br>
        <input type="submit" value="Update">
    </form>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/edit_product.html
{% extends "base.html" %}

{% block content %}
    <h1>Edit Product</h1>
    <form method="POST" action="{{ url_for('views.edit_product', product_id=product.id) }}">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" value="{{ product.name }}" required>
        <br>
        <label for="rate_per_unit">Rate per Unit:</label>
        <input type="number" step="0.01" id="rate_per_unit" name="rate_per_unit" value="{{ product.price }}" required>
        <br>
        <label for="quantity">Quantity:</label>
        <input type="number" step="0.01" id="quantity" name="quantity" value="{{ product.quantity }}" required>
        <br>
        <label for="section">Section:</label>
        <select id="section" name="section">
            {% for section in sections %}
                <option value="{{ section.id }}" {% if section.id == product.section_id %}selected{% endif %}>{{ section.name }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="unit">Unit:</label>
        <select id="unit" name="unit">
            {% for unit_option in unit_options %}
                <option value="{{ unit_option }}" {% if unit_option == product.unit %}selected{% endif %}>{{ unit_option }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="expiration_date">expiration_date:</label>
        <input type="text" id="expiration_date" name="expiration_date" value="{{ product.expiration_date }}" required>
        <br>
        <input type="submit" value="Update">
    </form>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/list_categories.html
{% extends "base2.html" %}

{% block content %}
    <h1>List of Categories</h1>
    <br>
    <div class="table-container">
    <table class="table table-striped custom-table">
        <thead>
            <tr>
                <th>Category Name</th>
                <th>Actions</th>
                <th>Products</th>
            </tr>
        </thead>
        <tbody>
            {% if categories %}
                {% for category in categories %}
                    <tr>
                        <td>{{ category.name }}</td>
                        <td>
                            <a href="{{ url_for('views.edit_category', category_id=category.id) }}" class="btn btn-secondary">Edit</a>
                            <a href="{{ url_for('views.delete_category', category_id=category.id) }}" class="btn btn-danger">Delete</a>
                        </td>
                        <td>
                            {% if category.products %}
                                <ul>
                                    {% for product in category.products %}
                                        <li>
                                            {{ product.name }} - Price: {{ product.rate_per_unit }} - Quantity: {{ product.quantity }}
                                            <a href="{{ url_for('views.edit_product', product_id=product.id) }}">Edit</a>
                                            <a href="{{ url_for('views.delete_product', product_id=product.id) }}">Delete</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <p>No products added.</p>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">No category created.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>
    
    <style>
        .custom-table {
            width: 100% !important; /* You can adjust this value as needed */
        }
    </style>
 
<div class="add-category-btn-container" style="position: fixed; bottom: 20px; right: 20px;">
    <a href="{{ url_for('views.create_category') }}" class="btn btn-primary">Create New Category</a>
</div>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/login.html
{% extends "base.html" %}
{%  block title %} Login {% endblock %}

{% block content %}
<form  method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
            />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
            />
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Login</button>

</form>
{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/summary.html
{% extends "base2.html" %}
{% block title %} Summary {% endblock %}

{% block content %}

<!-- Display heading and current date and time -->
<h1>Summary</h1>
<br>
<br>
<p>Date and Time: {{ current_datetime }}</p>
<br><br>
<!-- Display total sales -->
<h3>Weekly Sales:</h3>
<br>
<p>Total Sales: {{ total_sales }}</p>

<!-- Display the total sales per category table -->
<h3>Total Sales per Category:</h3>
<table>
  <tr>
    <th>Category</th>
    <th>Total Sales</th>
  </tr>
  {% for category in category_sales_data %}
  <tr>
    <td>{{ category }}</td>
    <td>{{ category_sales_data[category] }}</td>
  </tr>
  {% endfor %}
</table>
<br>
<br>
<br>
<!-- Display the out-of-stock products table -->
<h3>Out of Stock Products:</h3>
{% if out_of_stock_products %}
<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Category</th>
  </tr>
  {% for product in out_of_stock_products %}
  <tr>
    <td>{{ product['Product'] }}</td>
    <td>{{ product['Quantity'] }}</td>
    <td>{{ product['Category'] }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No products out of stock.</p>
{% endif %}

<br><br>
<h3>In Stock of Products:</h3>
{% if stock_products %}
<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Category</th>
  </tr>
  {% for product in stock_products %}
  <tr>
    <td>{{ product['Product'] }}</td>
    <td>{{ product['Quantity'] }}</td>
    <td>{{ product['Category'] }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No products in stock.</p>
{% endif %}

<br><br><br>


<!-- Display expired products -->
<h3>Expired Products:</h3>
{% if expired_products %}
<table>
  <tr>
    <th>Product</th>
    <th>Expiration Date</th>
    <th>Days to Expiration</th>
  </tr>
  {% for product in expired_products %}
  <tr>
    <td>{{ product.name }}</td>
    <td>{{ product.expiration_date }}</td>
    <td>Expired</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No expired products.</p>
{% endif %}
<br><br><br>
<!-- Display products expiring within 2 days -->
<h3>Products Expiring Within 2 Days:</h3>
{% if expiring_products %}
<table>
  <tr>
    <th>Product</th>
    <th>Expiration Date</th>
    <th>Days to Expiration</th>
  </tr>
  {% for product in expiring_products %}
  <tr>
    <td>{{ product.name }}</td>
    <td>{{ product.expiration_date }}</td>
    <td>{{ (product.expiration_date - current_datetime.date()).days }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No products expiring within 2 days.</p>
{% endif %}



<br><br><br>
<!-- Display the bar chart -->
<h3>Product Distribution:</h3>
{{ product_bar_chart_html|safe }}

<!-- Display the pie chart -->
<h3>Category Sales Distribution:</h3>
{{ category_pie_chart_html|safe }}


{% endblock %}

MAD-1-Grocery Store V1/grocery_app/templates/view_cart.html
{% extends "base2.html" %}

{% block content %}
    <h1>Shopping Cart</h1>
    <table>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>

        <!-- view_cart.html -->
        {% for cart_item in cart_items %}
        <tr>
            <td>{{ cart_item.product.name }}</td>
            <td>Rs.{{ cart_item.product.rate_per_unit }}</td>
            <td>{{ cart_item.quantity }}</td>
            <td>Rs.{{ cart_item.product.rate_per_unit * cart_item.quantity }}</td>
            <td><a href="{{ url_for('views.remove_from_cart', product_id=cart_item.product.id) }}" class="remove-button">Remove</a></td>
        </tr>
        {% endfor %}
    </table>
    <p class="total-amount">Total Amount: Rs.{{ total_amount }}</p>

    <!-- Add the Buy All button -->
    <div class="buy-all-button">
        <a href="{{ url_for('views.buy_all') }}" class="btn btn-success">Buy All</a>
    </div>
{% endblock %}